version: 0.2

env:
  variables:
    # Image name and image tag are set by the lambda that triggers this project
    IMAGE_NAME: ""
    IMAGE_TAG: ""
phases:
  pre_build:
    commands:
    - echo 'Pre_build_phase'
    - echo 'Testing tools BEGIN...'
    - aws --version
    - python --version
    - pip --version
    - git --version
    - echo "Installing required tools..."
    - pip install https://github.com/Longwave-innovation/gh-app-auth/releases/download/v0.2.0/gh_app_auth-0.2.0-py3-none-any.whl

    - echo "Saving private key to file..."
    - echo "$GITHUB_APP_PRIVATE_KEY" > private-key.pem

    - echo "Getting authenticated clone URL..."
    - |
      REPO_URL=$(gh-app-auth configure-git \
        --app-id $GITHUB_APP_ID \
        --installation-id $GITHUB_APP_INSTALL_ID \
        --private-key private_key.pem \
        --repo-owner $GITOPS_REPO_OWNER \
        --repo-name $GITOPS_REPO_NAME)
    - echo "Going to clone <$REPO_URL>"


    - echo "Configuring Git..."
    - git config --global user.email "$GIT_MAIL"
    - git config --global user.name "$GIT_USERNAME"

    - echo "TESTING CUSTOM ENV VARIABLES, IMAGE <$IMAGE_NAME> TAG <$IMAGE_TAG>"
  build:
    commands:
    - echo "Build_phase"
    - echo "Cloning repository <$REPO_URL>..."
    - git clone --depth 1 --branch main "$REPO_URL"
    - cd $GITOPS_REPO_NAME
    - pip install -r requirements.txt
    - python image_tag_updater.py -i $IMAGE_NAME -t $IMAGE_TAG -c image_tag_mappings.json
    - git add *
    - git commit -m "Automatic Pipeline - Updated image $IMAGE_NAME to version $IMAGE_TAG"
    - git push
  post_build:
    commands:
    - echo 'Post_build_phase'
