name: Generate terraform docs
on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.tf'
    - '**.hcl'
    - '.terraform.lock.hcl'
    - '**.md'
    - '.github/workflows/documentation.yaml'

jobs:

  tf-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git identity
      run: |
        git config --global user.email "innovation_r&d@longwave.it"
        git config --global user.name "ActionBot"

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.4.1
      with:
        working-dir: .
        config-file: .terraform-docs.yaml
        git-push: "true"
        git-commit-message: "docs: terraform-docs automated update"

  readme-toc:
    runs-on: ubuntu-latest
    needs: [ tf-docs ]
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js (for doctoc)
      uses: actions/setup-node@v6
      with:
        node-version: '22'

    - name: Install DocToc
      run: npm install -g doctoc

    - name: Generate / Update TOC in markdown README(s)
      run: |
        # generate or update TOC in all README files
        # --notitle removes the default "Table of Contents" header
        # --maxlevel can limit depth (e.g. 3) if desired
        doctoc ./README.md --notitle

    - name: Commit updated TOC(s) if changed
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "[skip ci] docs: updated TOC"
        branch: ${{ github.event.pull_request.head.ref }}

  lint-markdown:
    name: Markdown Linting
    needs: [ readme-toc ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:

    - name: Check out repository code
      uses: actions/checkout@v6

    - uses: DavidAnson/markdownlint-cli2-action@v22
      with:
        globs: |
          **/*.md
          !CHANGELOG.md
        fix: true

    - name: Set up Git identity
      run: |
        git config --global user.email "innovation_r&d@longwave.it"
        git config --global user.name "ActionBot"

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "[skip ci] docs: markdown lint fixes applied"
        branch: ${{ github.event.pull_request.head.ref }}
